# Generated by Django 6.0.3 on 2026-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rollo', models.CharField(max_length=50, unique=True)),
                ('material', models.CharField(max_length=100)),
                ('espesor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
