# Generated by Django 6.0.3 on 2026-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollo',
            name='peso_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rollo',
            name='espesor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
