# Generated by Django 6.0.3 on 2026-03-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rollo_peso_restante_alter_rollo_espesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollo',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='rollo',
            name='material',
            field=models.CharField(choices=[('Galvanizado', 'Galvanizado'), ('Crudo', 'Crudo'), ('Recocido RFR', 'Recocido RFR'), ('Aluminizado', 'Aluminizado'), ('Decapado', 'Decapado'), ('Rolado en caliente', 'Rolado en caliente')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rollo',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Patio A', 'Patio A'), ('Patio B', 'Patio B'), ('Almacen 1', 'Almacén 1'), ('Almacen 2', 'Almacén 2'), ('Produccion', 'Producción')], max_length=100, null=True),
        ),
    ]
