# Generated by Django 6.0.3 on 2026-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_rollo_estado_alter_rollo_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mp', models.CharField(max_length=50, unique=True)),
                ('tipo_mp', models.CharField(choices=[('Rollo', 'Rollo'), ('Cinta', 'Cinta'), ('Placa', 'Placa')], default='Rollo', max_length=20)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.CharField(choices=[('Galvanizado', 'Galvanizado'), ('Crudo', 'Crudo'), ('Recocido RFR', 'Recocido RFR'), ('Aluminizado', 'Aluminizado'), ('Decapado', 'Decapado'), ('Rolado en caliente', 'Rolado en caliente')], max_length=100)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('acabado', models.CharField(blank=True, max_length=50, null=True)),
                ('espesor_valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidad_espesor', models.CharField(choices=[('mm', 'mm'), ('pulg', 'Pulgadas'), ('calibre', 'Calibre')], default='mm', max_length=10)),
                ('espesor_mm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('espesor_pulg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('calibre', models.CharField(blank=True, max_length=20, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_restante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro_interior', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('diametro_exterior', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('ubicacion', models.CharField(blank=True, choices=[('Patio A', 'Patio A'), ('Patio B', 'Patio B'), ('Almacen 1', 'Almacén 1'), ('Almacen 2', 'Almacén 2'), ('Produccion', 'Producción')], max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='Disponible', max_length=50)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
