# Generated by Django 6.0.3 on 2026-03-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_materiaprima'),
        ('produccion', '0005_remove_ordenproduccion_rollo_ordenproduccion_mp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rollo',
        ),
    ]
