# Generated by Django 6.0.3 on 2026-03-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_delete_rollo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_mp/'),
        ),
    ]
