# Generated by Django 6.0.3 on 2026-04-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_materiaprima_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='origen_mp',
            field=models.CharField(choices=[('Propia', 'Propia'), ('Cliente', 'Cliente')], default='Propia', max_length=20),
        ),
    ]
