# Generated by Django 6.0.3 on 2026-04-14 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_materiaprima_cliente_materiaprima_origen_mp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='calibre',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='espesor_mm',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='espesor_pulg',
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='acabado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='diametro_exterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='diametro_interior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='espesor_valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='grado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='material',
            field=models.CharField(choices=[('Galvanizado', 'Galvanizado'), ('Crudo', 'Crudo'), ('Recocido RFR', 'Recocido RFR'), ('Aluminizado', 'Aluminizado'), ('Decapado', 'Decapado'), ('Rolado en caliente', 'Rolado en caliente'), ('Galvanizado y pintado', 'Galvanizado y pintado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='numero_mp',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='origen_mp',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Interna', 'Interna')], default='Interna', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo_mp',
            field=models.CharField(choices=[('Rollo', 'Rollo'), ('Placa', 'Placa'), ('Cinta', 'Cinta')], default='Rollo', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='ubicacion',
            field=models.CharField(choices=[('Patio A', 'Patio A'), ('Patio B', 'Patio B'), ('Almacén 1', 'Almacén 1'), ('Almacén 2', 'Almacén 2'), ('Producción', 'Producción')], default='Almacén 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_espesor',
            field=models.CharField(choices=[('mm', 'mm'), ('pulg', 'pulg'), ('calibre', 'calibre')], default='mm', max_length=20),
        ),
    ]
