# Generated by Django 6.0.3 on 2026-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_materiaprima_calibre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
