# Generated by Django 6.0.3 on 2026-04-27 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_cliente_codigo_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='estado',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='Disponible', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='material',
            field=models.CharField(blank=True, choices=[('Galvanizado', 'Galvanizado'), ('Crudo', 'Crudo'), ('Recocido RFR', 'Recocido RFR'), ('Aluminizado', 'Aluminizado'), ('Decapado', 'Decapado'), ('Rolado en caliente', 'Rolado en caliente'), ('Galvanizado y pintado', 'Galvanizado y pintado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Patio A', 'Patio A'), ('Patio B', 'Patio B'), ('Almacén 1', 'Almacén 1'), ('Almacén 2', 'Almacén 2'), ('Producción', 'Producción')], default='Almacén 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_espesor',
            field=models.CharField(blank=True, choices=[('mm', 'mm'), ('pulg', 'pulg'), ('calibre', 'calibre')], default='mm', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MovimientoMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('CONSUMO', 'Consumo'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('MERMA', 'Merma'), ('TRASPASO', 'Traspaso'), ('SALIDA', 'Salida')], max_length=30)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ubicacion_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.materiaprima')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
