# Generated by Django 5.0.6 on 2026-05-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_materiaprima_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='archivo_pdf',
        ),
    ]
