# Generated by Django 5.0.6 on 2026-07-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_materiaprima_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='mp_pdfs/'),
        ),
    ]
