# Generated by Django 5.0.6 on 2026-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_materiaprima_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='material',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
