# Generated by Django 5.0.6 on 2026-07-22 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_materiaprima_material_texto_libre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientomp',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
