# Generated by Django 5.0.6 on 2026-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0015_movimiento_fecha_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiaprima",
            name="unidad_espesor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mils", "Milésimas de pulgada (mils)"),
                    ("mm", "mm"),
                    ("pulg", "pulg"),
                    ("calibre", "calibre"),
                ],
                default="mils",
                max_length=20,
                null=True,
            ),
        ),
    ]
