# Generated by Django 5.0.6 on 2026-05-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0012_remove_materiaprima_archivo_pdf'),
        ('produccion', '0007_alter_detalleslitter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pt', models.CharField(max_length=100, unique=True)),
                ('tipo_proceso', models.CharField(max_length=30)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_paquetes', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_piezas', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en_almacen', 'En Almacén'), ('vendido', 'Vendido'), ('embarcado', 'Embarcado')], default='en_almacen', max_length=20)),
                ('ubicacion', models.CharField(blank=True, default='Almacén PT', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producto_terminado', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Producto Terminado',
                'verbose_name_plural': 'Productos Terminados',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
