# Generated by Django 5.0.6 on 2026-07-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_terminada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='tipo_producto',
            field=models.CharField(choices=[('cinta', 'Cinta'), ('fleje', 'Fleje'), ('otro', 'Otro')], default='cinta', max_length=20),
        ),
    ]
