# Generated by Django 5.0.6 on 2026-07-20 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_materiaprima_material_texto_libre'),
        ('materia_terminada', '0002_agregar_tipo_producto_pt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_remision', models.CharField(blank=True, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('maquila', 'Maquila (al cliente)'), ('interno', 'Interno (Centro de Servicio)')], max_length=20)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='SalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_piezas', models.PositiveIntegerField(blank=True, null=True)),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_detalle', to='materia_terminada.productoterminado')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='materia_terminada.salida')),
            ],
        ),
    ]
