# Generated by Django 5.0.6 on 2026-07-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_terminada', '0003_agregar_salida_y_detalle'),
        ('produccion', '0008_agregar_pt_origen_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='detalle_slitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_terminado', to='produccion.detalleslitter'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_terminados', to='produccion.ordenproduccion'),
        ),
    ]
