# Generated by Django 5.0.6 on 2026-08-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_terminada', '0004_pt_fk_multiple_y_detalle_slitter'),
        ('produccion', '0010_ordenproduccion_demora_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='detalle_fleje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_terminado', to='produccion.detallefleje'),
        ),
    ]
