# Generated by Django 5.0.6 on 2026-08-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materia_terminada", "0005_productoterminado_detalle_fleje"),
        ("produccion", "0013_detalleslitter_peso_merma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoterminado",
            name="orden",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos_terminados",
                to="produccion.ordenproduccion",
            ),
        ),
        migrations.AlterField(
            model_name="salidadetalle",
            name="producto_terminado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salida_detalle",
                to="materia_terminada.productoterminado",
            ),
        ),
    ]
