# Generated by Django 5.0.6 on 2026-08-18 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0015_movimiento_fecha_editable"),
        ("materia_terminada", "0006_alter_productoterminado_orden_and_more"),
        ("produccion", "0014_alter_ordenproduccion_mp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("mp", "Materia Prima"), ("pt", "Producto Terminado")],
                        max_length=10,
                    ),
                ),
                ("numero_certificado", models.CharField(blank=True, max_length=100)),
                (
                    "numero_colada",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="No. de colada / heat number",
                    ),
                ),
                (
                    "norma",
                    models.CharField(
                        blank=True,
                        help_text="Ej. ASTM A1008, ASTM A653, NOM-, etc.",
                        max_length=150,
                    ),
                ),
                (
                    "limite_fluencia_mpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Límite de fluencia (MPa)",
                    ),
                ),
                (
                    "resistencia_tension_mpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Resistencia a la tensión (MPa)",
                    ),
                ),
                (
                    "elongacion_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Elongación (%)",
                    ),
                ),
                (
                    "dureza",
                    models.CharField(blank=True, max_length=50, verbose_name="Dureza"),
                ),
                ("proveedor_emisor", models.CharField(blank=True, max_length=150)),
                ("fecha_emision", models.DateField(blank=True, null=True)),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="certificados_calidad/"
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar si el certificado no cumple la especificación del pedido.",
                        verbose_name="Aprobado por calidad",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "mp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="inventario.materiaprima",
                        verbose_name="Materia Prima",
                    ),
                ),
                (
                    "producto_terminado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="materia_terminada.productoterminado",
                        verbose_name="Producto Terminado",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de calidad",
                "verbose_name_plural": "Certificados de calidad",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="NoConformidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("dimensional", "Dimensional"),
                            ("superficial", "Superficial / acabado"),
                            ("material", "Material / composición"),
                            ("empaque", "Empaque / embalaje"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("menor", "Menor"),
                            ("mayor", "Mayor"),
                            ("critica", "Crítica"),
                        ],
                        default="menor",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_revision", "En revisión"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("accion_correctiva", models.TextField(blank=True)),
                (
                    "evidencia_foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="no_conformidades/"
                    ),
                ),
                ("fecha_deteccion", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "detectado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="no_conformidades_detectadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_conformidades",
                        to="inventario.materiaprima",
                        verbose_name="Materia Prima",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_conformidades",
                        to="produccion.ordenproduccion",
                    ),
                ),
                (
                    "producto_terminado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_conformidades",
                        to="materia_terminada.productoterminado",
                        verbose_name="Producto Terminado",
                    ),
                ),
            ],
            options={
                "verbose_name": "No conformidad",
                "verbose_name_plural": "No conformidades",
                "ordering": ["-fecha_deteccion"],
            },
        ),
        migrations.CreateModel(
            name="ToleranciaProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_proceso",
                    models.CharField(
                        choices=[
                            ("slitter", "Slitter"),
                            ("corte_liso", "Corte Liso"),
                            ("mini_slitter", "Mini Slitter"),
                            ("fleje", "Fleje"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="Déjalo vacío para que aplique a todos los materiales de este proceso.",
                        max_length=150,
                    ),
                ),
                (
                    "tolerancia_ancho_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Tolerancia de ancho (± mm)",
                    ),
                ),
                (
                    "tolerancia_espesor_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="Tolerancia de espesor (± mm)",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tolerancia de proceso",
                "verbose_name_plural": "Tolerancias de proceso",
                "ordering": ["tipo_proceso", "material"],
                "unique_together": {("tipo_proceso", "material")},
            },
        ),
    ]
