# Generated by Django 5.0.6 on 2026-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionempresa',
            name='logo',
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='logo_url',
            field=models.URLField(blank=True, default='', verbose_name='URL del logo'),
        ),
    ]
