# Generated by Django 5.0.6 on 2026-06-10 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_configuracionempresa_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField()),
                ('objeto_str', models.CharField(blank=True, max_length=200)),
                ('accion', models.CharField(choices=[('CREAR', 'Creado'), ('EDITAR', 'Editado'), ('ESTADO', 'Cambio de estado'), ('MOVIMIENTO', 'Movimiento registrado')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de cambio',
                'ordering': ['-fecha'],
            },
        ),
    ]
