# Generated by Django 5.0.6 on 2026-08-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_limpiar_datos_operacionales_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creado'), ('EDITAR', 'Editado'), ('ESTADO', 'Cambio de estado'), ('MOVIMIENTO', 'Movimiento registrado'), ('ELIMINAR', 'Eliminado')], max_length=20),
        ),
    ]
