# Generated by Django 6.0.3 on 2026-03-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=50)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.lineaproduccion')),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.rollo')),
            ],
        ),
    ]
