# Generated by Django 6.0.3 on 2026-03-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_cliente'),
        ('produccion', '0002_ordenproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='folio_orden',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='peso_usado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
