# Generated by Django 6.0.3 on 2026-03-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_ordenproduccion_cliente_ordenproduccion_folio_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='peso_producido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_merma', models.CharField(choices=[('Desorille', 'Desorille'), ('Punta y final', 'Punta y final'), ('Donas', 'Donas')], max_length=50)),
                ('peso_merma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
            ],
        ),
    ]
