# Generated by Django 6.0.3 on 2026-03-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_materiaprima'),
        ('produccion', '0004_ordenproduccion_peso_producido_merma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='rollo',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='mp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiaprima'),
        ),
        migrations.CreateModel(
            name='RequerimientoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_salida', models.CharField(blank=True, max_length=200, null=True)),
                ('toneladas_totales_aprox', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro_interior_entrada_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('diametro_interior_entrada_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('diametro_exterior_entrada_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peso_rc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_rc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro_interior_salida', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tolerancia', models.CharField(blank=True, max_length=100, null=True)),
                ('toneladas_por_cinta_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('toneladas_por_cinta_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_cintas', models.IntegerField(blank=True, null=True)),
                ('ancho_cinta', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rendimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('merma', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('util', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desorille', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_maximo_por_cinta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('peso_estimado_paquete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instrucciones_entrega', models.TextField(blank=True, null=True)),
                ('instrucciones_flejado', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='produccion.ordenproduccion')),
            ],
        ),
    ]
