# Generated by Django 6.0.3 on 2026-04-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_remove_ordenproduccion_rollo_ordenproduccion_mp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requerimientoproduccion',
            name='orden',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_paquetes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_piezas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='merma_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='rendimiento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='tiempo_muerto_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='tiempo_preparacion_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='tiempo_proceso_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='turno',
            field=models.CharField(blank=True, choices=[('1', 'Turno 1'), ('2', 'Turno 2'), ('3', 'Turno 3')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DetalleSlitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_corte', models.PositiveIntegerField()),
                ('ancho', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('espesor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rebaba', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('camber', models.CharField(blank=True, max_length=100, null=True)),
                ('material_ok', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_slitter', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.operador'),
        ),
        migrations.DeleteModel(
            name='Merma',
        ),
        migrations.DeleteModel(
            name='RequerimientoProduccion',
        ),
    ]
