# Generated by Django 6.0.3 on 2026-04-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_operador_remove_requerimientoproduccion_orden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleslitter',
            options={'ordering': ['no_corte']},
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='scrap_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='tipo_proceso',
            field=models.CharField(choices=[('slitter', 'Slitter'), ('corte_liso', 'Corte Liso'), ('mini_slitter', 'Mini Slitter'), ('fleje', 'Fleje')], default='slitter', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='folio_orden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='detalleslitter',
            unique_together={('orden', 'no_corte')},
        ),
    ]
