# Generated by Django 5.0.6 on 2026-07-16 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_terminada', '0002_agregar_tipo_producto_pt'),
        ('produccion', '0007_alter_detalleslitter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='pt_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_flejado', to='materia_terminada.productoterminado'),
        ),
    ]
