# Generated by Django 5.0.6 on 2026-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_agregar_pt_origen_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='operador',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='operador_nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Operador'),
        ),
    ]
