# Generated by Django 5.0.6 on 2026-08-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_operador_texto_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='demora_hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='demora_hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='espesor_rollo_padre',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='folio_rollo_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='peso_rollo_padre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='temp_zona_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Zona 1'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='temp_zona_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Zona 2'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='temp_zona_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Zona 3'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='temp_zona_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Zona 4'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='temp_zona_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Zona 5'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='tipo_fleje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DetalleFleje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_fleje', models.PositiveIntegerField()),
                ('folio_descarga', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_rebaba', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('numero_descarga', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_descarga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('numero_flejes', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_fleje', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['no_fleje'],
                'unique_together': {('orden', 'no_fleje')},
            },
        ),
    ]
