# Generated by Django 5.0.6 on 2026-08-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_ordenproduccion_demora_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_orden_corte',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de orden de corte'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_produccion_oc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de producción de OC'),
        ),
    ]
