# Generated by Django 5.0.6 on 2026-08-12 15:16

from django.db import migrations, models


def migrar_material_ok_a_clasificacion(apps, schema_editor):
    DetalleSlitter = apps.get_model('produccion', 'DetalleSlitter')
    DetalleSlitter.objects.filter(material_ok=False).update(clasificacion='descarte')


def revertir_clasificacion_a_material_ok(apps, schema_editor):
    DetalleSlitter = apps.get_model('produccion', 'DetalleSlitter')
    DetalleSlitter.objects.filter(clasificacion='normal').update(material_ok=True)
    DetalleSlitter.objects.exclude(clasificacion='normal').update(material_ok=False)


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_ordenproduccion_fecha_orden_corte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleslitter',
            name='clasificacion',
            field=models.CharField(choices=[('normal', 'Normal'), ('scrap', 'Scrap'), ('descarte', 'Descarte')], default='normal', max_length=20),
        ),
        migrations.RunPython(
            migrar_material_ok_a_clasificacion,
            revertir_clasificacion_a_material_ok,
        ),
        migrations.RemoveField(
            model_name='detalleslitter',
            name='material_ok',
        ),
    ]
