# Generated by Django 5.0.6 on 2026-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_detalleslitter_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleslitter',
            name='peso_merma',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso real (pesado aparte) del sobrante cuando el corte se clasifica como Scrap o Descarte.', max_digits=10, null=True, verbose_name='Peso scrap/descarte'),
        ),
    ]
