# Generated by Django 5.0.6 on 2026-08-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0015_movimiento_fecha_editable"),
        ("produccion", "0013_detalleslitter_peso_merma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenproduccion",
            name="mp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario.materiaprima",
            ),
        ),
    ]
